name: flutter_version_manager
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.17+855

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ## DATA HANDLE PACKAGES
  # This lib to set windows size on Windows.
  window_manager: ^0.4.2
  http: ^1.2.1
  # A Flutter plugin for finding commonly used locations on the filesystem
  path_provider: ^2.1.3
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.0
  # Save settings
  shared_preferences: ^2.3.2
  ##
  # Package for Packaging Windows App
  msix: ^3.16.8
  # State management combination
  flutter_bloc: ^8.1.6
  # Open link
  url_launcher: ^6.3.0
  # create route for application, it is now 05/05/2024 required to stick to ^12.1.3 to get PopScope to work properly
  go_router: 12.1.3
  collection: ^1.18.0
  # The path package provides common operations for manipulating paths: joining, splitting, normalizing, etc
  path: ^1.9.0
  image_picker: ^1.1.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  ### UI PACKAGES
  responsive_builder: ^0.7.0
  loading_indicator: ^3.1.1
  # use for customizing theme
  dynamic_color: ^1.7.0
  # localization
  flutter_localization: ^0.2.0
  flutter_localizations:
    sdk: flutter
  i18n_extension: ^12.0.1
  # custom icon
  flutter_sizer: ^1.0.5
  device_info_plus: ^10.1.2
  http_parser: ^4.0.2
  equatable: ^2.0.5
  file_picker: ^8.0.6
  open_file_plus: ^3.4.1+1
  intl: ^0.19.0
  string_validator: ^1.1.0
  windows_status_bar:
    git: https://github.com/tranhuudang/windows_status_bar
  dotted_border: ^2.1.0
  upgrader: ^10.3.0
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^10.7.0
  loading_animation_widget: ^1.3.0
  fluentui_system_icons: ^1.1.271
  google_fonts: ^6.2.1
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  cached_network_svg_image: ^1.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  freezed: any
  json_serializable: ^6.8.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/release_notes/release_notes.json
    - assets/badges/
    - assets/images/app_icon.png
    - assets/donation/
msix_config:
  display_name: Flutter Version Manager
  publisher_display_name: Zeroboy
  identity_name: 24555Zeroboy.FlutterVersionManager
  publisher: CN=DA7D2C99-987C-4B69-8953-17157F6E0E1A
  msix_version: 2025.2.24.0
  trim_logo: false
  logo_path: C:\Users\tranh\StudioProjects\new\flutter_version_manager\assets\images\app-icon.png
  store: true
  language: en-us, vi-vi, zh-cn